version: "3.8"

services:
  postgres:
    image: postgres:16.2
    ports:
      - 15432:5432
    volumes:
      - forest_of_habits:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=forest_of_habits
volumes:
  forest_of_habits:
